#! /bin/sh
if [ "$#" -ne 7 ]; then
  echo "Illegal number of parameters, exiting."
  echo "Usage: rundbm [outputFile] [clientIPStartIndex] [clientIPEndIndex] [NumaMemNode] [NumaSocketNode] [NumaCPUs] [trialNo]"
  exit  
fi
od="$1-t$7"
echo "Output directory: $od"
if [ ! -d "$od" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  echo "Output directory does not exist, creating one"
  mkdir $od
  echo "created"
fi
echo "Number of clients: $3"
e=$(($2+$3-1))
for i in `seq $2 $e`; do
  cmd="numactl -m $4 -N $5 -C $6 ./runcl -nid$i > $od/c$i.out &"
  #cmd="numactl -m $4 -N $5 -C $6 ./runcl -nid$i"
  echo "running: $cmd"
  eval $cmd
done
#./halstead/monitorThreads.sh runcl 1
