#! /bin/sh
if [ "$#" -ne 7 ]; then
  echo "Illegal number of parameters, exiting."
  exit  
fi
od="$1-t$7"
echo "Output directory: $od"
if [ ! -d "$od" ]; then
  echo "Output directory does not exist, creating one"
  mkdir $od
  echo "created"
fi
echo "Number of servers: $3"
e=$(($2+$3-1))
for i in `seq $2 $e`; do
  cmd="./rundb -nid$i -o $od/s$i.out &"
  cmd_numactl="numactl -m $4 -N $5 -C $6 ./rundb -nid$i > $od/s$i.out &"
  cmd_taskset="taskset -c 0-7 ./rundb -nid$i > $od/s$i.out &"
  echo "running: $cmd_numactl"
  eval $cmd_numactl
done
#./halstead/monitorThreads.sh rundb 1
