- hosts: all
  tasks:
  - name: Update Apt
    become: yes
    apt: update_cache=yes cache_valid_time=36000

  - name: Install dependencies
    become: yes
    apt:
      name: "{{ deps }}" # located in group_vars/all
      state: present

  - name: Syncronizing ExpoDB Codebase
    synchronize:
      src: ../../
      dest: ~/expodb

  - name: Create build directory
    file:
      state: directory
      path: ~/expodb-build

  - name: Build code
    command: "{{ item }} chdir=~/expodb-build"
    with_items:
      - cmake ~/expodb
      - make

  - name: Copy ifconfig.txt
    command: "cp ~/expodb/ifconfig.txt ~/expodb-build/ifconfig.txt"