# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ quecc-dist ]
  pull_request:
    branches: [ quecc-dist ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: deploy to staging
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo installing softwar dependencies.
        sudo apt-get install -y cmake libboost-atomic-dev libnuma-dev libyaml-dev libnanomsg-dev libjemalloc-dev python3
        echo setting up Python3 as default.
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    
    - name: Start build
      run:
        mkdir qcd-build; cd qcd-build
        cmake ../
        make
    
    # Runs local tests using GoogleTests
    - name: Run tests
      run: 
        ./bin/config_yaml_test
