# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ quecc-dist ]
  pull_request:
    branches: [ quecc-dist ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Q-store build
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install libraries/packages
      run: |
        echo installing softwar dependencies.
        sudo apt-get install -y cmake libboost-atomic-dev libnuma-dev libyaml-dev libnanomsg-dev libjemalloc-dev libzookeeper-mt-dev python3
        echo setting up Python3 as default.
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

    - name: Create build directory
      run: mkdir ${{ github.workspace }}/qcd-build

    - name: Change to build directory
      run: cd ${{ github.workspace }}/qcd-build

    - name: Run CMake directory
      run: cmake ${{ github.workspace }}

    - name: Build binaries
      run: make -j2

      # Runs local tests using GoogleTests
    - name: Run tests
      run: bin/config_yaml_test
